class booking_seat_dictionary():
	def __init__(self):
		pass
	def return_correct_query(tableName, row):
		booking_query_dict = { #CHALLENGE WRITE A PYTHON SCRIPT TO WRITE CODE SO I DONT HAVE TO DO THIS CRAP
			("Hamatsu","ROW A"):"""UPDATE car_seating_Hamatsu SET ROW_A = %s WHERE carID = %s""",
			("Hamatsu","ROW B"):"""UPDATE car_seating_Hamatsu SET ROW_B = %s WHERE carID = %s""",
			("Hamatsu","ROW C"):"""UPDATE car_seating_Hamatsu SET ROW_C = %s WHERE carID = %s""",
			("Hamatsu","ROW D"):"""UPDATE car_seating_Hamatsu SET ROW_D = %s WHERE carID = %s""",
			("Hamatsu", "ROW E"):"""UPDATE car_seating_Hamatsu SET ROW_E = %s WHERE carID = %s""",
			("Hamatsu", "ROW F"):"""UPDATE car_seating_Hamatsu SET ROW_F = %s WHERE carID = %s""",
			("Hamatsu", "ROW G"): """UPDATE car_seating_Hamatsu SET ROW_G = %s WHERE carID = %s""",
			("Hamatsu", "ROW H"):"""UPDATE car_seating_Hamatsu SET ROW_H = %s WHERE carID = %s""",
			("Kyoto","ROW A"):"""UPDATE car_seating_Kyoto SET ROW_A = %s WHERE carID = %s""",
			("Kyoto","ROW B"):"""UPDATE car_seating_Kyoto SET ROW_B = %s WHERE carID = %s""",
			("Kyoto","ROW C"):"""UPDATE car_seating_Kyoto SET ROW_C = %s WHERE carID = %s""",
			("Kyoto","ROW D"):"""UPDATE car_seating_Kyoto SET ROW_D = %s WHERE carID = %s""",
			("Kyoto", "ROW E"):"""UPDATE car_seating_Kyoto SET ROW_E = %s WHERE carID = %s""",
			("Kyoto", "ROW F"):"""UPDATE car_seating_Kyoto SET ROW_F = %s WHERE carID = %s""",
			("Kyoto", "ROW G"): """UPDATE car_seating_Kyoto SET ROW_F = %s WHERE carID = %s""",
			("Kyoto", "ROW H"):"""UPDATE car_seating_Kyoto SET ROW_H = %s WHERE carID = %s""",
			("Maibara","ROW A"):"""UPDATE car_seating_Maibara SET ROW_A = %s WHERE carID = %s""",
			("Maibara","ROW B"):"""UPDATE car_seating_Maibara SET ROW_B = %s WHERE carID = %s""",
			("Maibara","ROW C"):"""UPDATE car_seating_Maibara SET ROW_C = %s WHERE carID = %s""",
			("Maibara","ROW D"):"""UPDATE car_seating_Maibara SET ROW_D = %s WHERE carID = %s""",
			("Maibara", "ROW E"):"""UPDATE car_seating_Maibara SET ROW_E = %s WHERE carID = %s""",
			("Maibara", "ROW F"):"""UPDATE car_seating_Maibara SET ROW_F = %s WHERE carID = %s""",
			("Maibara", "ROW G"): """UPDATE car_seating_Maibara SET ROW_F = %s WHERE carID = %s""",
			("Maibara", "ROW H"):"""UPDATE car_seating_Maibara SET ROW_H = %s WHERE carID = %s""",
			("Mishima","ROW A"):"""UPDATE car_seating_Mishima SET ROW_A = %s WHERE carID = %s""",
			("Mishima","ROW B"):"""UPDATE car_seating_Mishima SET ROW_B = %s WHERE carID = %s""",
			("Mishima","ROW C"):"""UPDATE car_seating_Mishima SET ROW_C = %s WHERE carID = %s""",
			("Mishima","ROW D"):"""UPDATE car_seating_Mishima SET ROW_D = %s WHERE carID = %s""",
			("Mishima", "ROW E"):"""UPDATE car_seating_Mishima SET ROW_E = %s WHERE carID = %s""",
			("Mishima", "ROW F"):"""UPDATE car_seating_Mishima SET ROW_F = %s WHERE carID = %s""",
			("Mishima", "ROW G"): """UPDATE car_seating_Mishima SET ROW_F = %s WHERE carID = %s""",
			("Mishima", "ROW H"):"""UPDATE car_seating_Mishima SET ROW_H = %s WHERE carID = %s""",
			("Nagoya","ROW A"):"""UPDATE car_seating_Nagoya SET ROW_A = %s WHERE carID = %s""",
			("Nagoya","ROW B"):"""UPDATE car_seating_Nagoya SET ROW_B = %s WHERE carID = %s""",
			("Nagoya","ROW C"):"""UPDATE car_seating_Nagoya SET ROW_C = %s WHERE carID = %s""",
			("Nagoya","ROW D"):"""UPDATE car_seating_Nagoya SET ROW_D = %s WHERE carID = %s""",
			("Nagoya", "ROW E"):"""UPDATE car_seating_Nagoya SET ROW_E = %s WHERE carID = %s""",
			("Nagoya", "ROW F"):"""UPDATE car_seating_Nagoya SET ROW_F = %s WHERE carID = %s""",
			("Nagoya", "ROW G"): """UPDATE car_seating_Nagoya SET ROW_F = %s WHERE carID = %s""",
			("Nagoya", "ROW H"):"""UPDATE car_seating_Nagoya SET ROW_H = %s WHERE carID = %s""",
			("ShinYokohama","ROW A"):"""UPDATE car_seating_ShinYokohama SET ROW_A = %s WHERE carID = %s""",
			("ShinYokohama","ROW B"):"""UPDATE car_seating_ShinYokohama SET ROW_B = %s WHERE carID = %s""",
			("ShinYokohama","ROW C"):"""UPDATE car_seating_ShinYokohama SET ROW_C = %s WHERE carID = %s""",
			("ShinYokohama","ROW D"):"""UPDATE car_seating_ShinYokohama SET ROW_D = %s WHERE carID = %s""",
			("ShinYokohama", "ROW E"):"""UPDATE car_seating_ShinYokohama SET ROW_E = %s WHERE carID = %s""",
			("ShinYokohama", "ROW F"):"""UPDATE car_seating_ShinYokohama SET ROW_F = %s WHERE carID = %s""",
			("ShinYokohama", "ROW G"): """UPDATE car_seating_ShinYokohama SET ROW_F = %s WHERE carID = %s""",
			("ShinYokohama", "ROW H"):"""UPDATE car_seating_ShinYokohama SET ROW_H = %s WHERE carID = %s""",
			("Shizuoka","ROW A"):"""UPDATE car_seating_Shizuoka SET ROW_A = %s WHERE carID = %s""",
			("Shizuoka","ROW B"):"""UPDATE car_seating_Shizuoka SET ROW_B = %s WHERE carID = %s""",
			("Shizuoka","ROW C"):"""UPDATE car_seating_Shizuoka SET ROW_C = %s WHERE carID = %s""",
			("Shizuoka","ROW D"):"""UPDATE car_seating_Shizuoka SET ROW_D = %s WHERE carID = %s""",
			("Shizuoka", "ROW E"):"""UPDATE car_seating_Shizuoka SET ROW_E = %s WHERE carID = %s""",
			("Shizuoka", "ROW F"):"""UPDATE car_seating_Shizuoka SET ROW_F = %s WHERE carID = %s""",
			("Shizuoka", "ROW G"): """UPDATE car_seating_Shizuoka SET ROW_F = %s WHERE carID = %s""",
			("Shizuoka", "ROW H"):"""UPDATE car_seating_Shizuoka SET ROW_H = %s WHERE carID = %s""",
			("Tokyo","ROW A"):"""UPDATE car_seating_Tokyo SET ROW_A = %s WHERE carID = %s""",
			("Tokyo","ROW B"):"""UPDATE car_seating_Tokyo SET ROW_B = %s WHERE carID = %s""",
			("Tokyo","ROW C"):"""UPDATE car_seating_Tokyo SET ROW_C = %s WHERE carID = %s""",
			("Tokyo","ROW D"):"""UPDATE car_seating_Tokyo SET ROW_D = %s WHERE carID = %s""",
			("Tokyo", "ROW E"):"""UPDATE car_seating_Tokyo SET ROW_E = %s WHERE carID = %s""",
			("Tokyo", "ROW F"):"""UPDATE car_seating_Tokyo SET ROW_F = %s WHERE carID = %s""",
			("Tokyo", "ROW G"): """UPDATE car_seating_Tokyo SET ROW_F = %s WHERE carID = %s""",
			("Tokyo", "ROW H"):"""UPDATE car_seating_Tokyo SET ROW_H = %s WHERE carID = %s"""
		}
		booking_query = booking_query_dict.get((tableName, row))
		return booking_query